
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sirens;

/**
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form NewJFrame
     */
    public MainFrame ()
    {
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents ()
    {

        // Variables declaration - do not modify
        javax.swing.JToggleButton jToggleButton1 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton4 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton7 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton5 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton3 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton2 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton8 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton6 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton10 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton9 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton11 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton12 = new javax.swing.JToggleButton ();

        setDefaultCloseOperation (javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane ().setLayout (new java.awt.GridLayout (3, 3));

        jToggleButton1.setText ("HiLo");
        jToggleButton1.addActionListener (evt ->
                ClipHandler.startStop ("Code3HiLo.wav"));
        getContentPane ().add (jToggleButton1);

        jToggleButton4.setText ("Horn");
        jToggleButton4.addActionListener (evt ->
                ClipHandler.startStop ("Code3Horn.wav"));
        getContentPane ().add (jToggleButton4);

        jToggleButton7.setText ("HyperYelp");
        jToggleButton7.addActionListener (evt ->
                ClipHandler.startStop ("Code3HyperYelp.wav"));
        getContentPane ().add (jToggleButton7);

        jToggleButton5.setText ("Wail");
        jToggleButton5.addActionListener (evt ->
                ClipHandler.startStop ("Code3Wail.wav"));
        getContentPane ().add (jToggleButton5);

        jToggleButton3.setText ("Yelp");
        jToggleButton3.addActionListener (evt ->
                ClipHandler.startStop ("Code3Yelp.wav"));
        getContentPane ().add (jToggleButton3);

        jToggleButton2.setText ("FedHilo");
        jToggleButton2.addActionListener (evt ->
                ClipHandler.startStop ("FedSigHiLo.wav"));
        getContentPane ().add (jToggleButton2);

        jToggleButton8.setText ("FedHorn");
        jToggleButton8.addActionListener (evt ->
                ClipHandler.startStop ("FedSigHorn.wav"));
        getContentPane ().add (jToggleButton8);

        jToggleButton6.setText ("FedYelp");
        jToggleButton6.addActionListener (evt ->
                ClipHandler.startStop ("FedSigYelp.wav"));
        getContentPane ().add (jToggleButton6);

        jToggleButton10.setText ("NHorn");
        jToggleButton10.addActionListener (evt ->
                ClipHandler.startStop ("galls_newhorn.wav"));
        getContentPane ().add (jToggleButton10);

        jToggleButton9.setText ("NSiren");
        jToggleButton9.addActionListener (evt ->
                ClipHandler.startStop ("galls_newqsiren.wav"));
        getContentPane ().add (jToggleButton9);

        jToggleButton11.setText ("NThunder");
        jToggleButton11.addActionListener (evt ->
                ClipHandler.startStop ("galls_newthunder.wav"));
        getContentPane ().add (jToggleButton11);

        jToggleButton12.setText ("Equinox");
        jToggleButton12.addActionListener (evt ->
                ClipHandler.startStop ("EquinoxWail.wav"));
        getContentPane ().add (jToggleButton12);

        pack ();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main (String[] args)
    {
        MainFrame jf = new MainFrame ();
        jf.setTitle ("YelpMachine!");
        jf.setVisible (true);
    }
}
