
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sirens;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.Line;
import java.io.File;
import java.io.InputStream;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        // Variables declaration - do not modify
        javax.swing.JToggleButton jToggleButton1 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton4 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton7 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton5 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton3 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton2 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton8 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton6 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton10 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton9 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton11 = new javax.swing.JToggleButton ();
        javax.swing.JToggleButton jToggleButton12 = new javax.swing.JToggleButton ();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        jToggleButton1.setText("HiLo");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);
        getContentPane().add(jToggleButton1);

        jToggleButton4.setText("Horn");
        jToggleButton4.addActionListener(this::jToggleButton4ActionPerformed);
        getContentPane().add(jToggleButton4);

        jToggleButton7.setText("HyperYelp");
        jToggleButton7.addActionListener(this::jToggleButton7ActionPerformed);
        getContentPane().add(jToggleButton7);

        jToggleButton5.setText("Wail");
        jToggleButton5.addActionListener(this::jToggleButton5ActionPerformed);
        getContentPane().add(jToggleButton5);

        jToggleButton3.setText("Yelp");
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);
        getContentPane().add(jToggleButton3);

        jToggleButton2.setText("FedHilo");
        jToggleButton2.addActionListener(this::jToggleButton2ActionPerformed);
        getContentPane().add(jToggleButton2);

        jToggleButton8.setText("FedHorn");
        jToggleButton8.addActionListener(this::jToggleButton8ActionPerformed);
        getContentPane().add(jToggleButton8);

        jToggleButton6.setText("FedYelp");
        jToggleButton6.addActionListener(this::jToggleButton6ActionPerformed);
        getContentPane().add(jToggleButton6);

        jToggleButton10.setText("NHorn");
        jToggleButton10.addActionListener(this::jToggleButton10ActionPerformed);
        getContentPane().add(jToggleButton10);

        jToggleButton9.setText("NSiren");
        jToggleButton9.addActionListener(this::jToggleButton9ActionPerformed);
        getContentPane().add(jToggleButton9);

        jToggleButton11.setText("NThunder");
        jToggleButton11.addActionListener(this::jToggleButton11ActionPerformed);
        getContentPane().add(jToggleButton11);

        jToggleButton12.setText("");
        jToggleButton12.addActionListener(this::jToggleButton12ActionPerformed);
        getContentPane().add(jToggleButton12);

        pack();
    }// </editor-fold>

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("Code3HiLo.wav");
    }

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("Code3Horn.wav");
    }

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("Code3HyperYelp.wav");
    }

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("Code3Wail.wav");
    }

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("Code3Yelp.wav");
    }

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("FedSigHiLo.wav");
    }

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("FedSigHorn.wav");
    }

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("FedSigYelp.wav");
    }

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("galls_newhorn.wav");
    }

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("galls_newqsiren.wav");
    }

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt)
    {
        ClipHandler.startStop ("galls_newthunder.wav");
    }

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args)
    {
        MainFrame jf = new MainFrame();
        jf.setTitle ("YelpMachine!");
        jf.setVisible(true);
    }
}
